### ISSUE TITLE
Paragraph text is too high contrast

### ISSUE THREAD

**Issue by Poorchop** [StylishThemes/Wikipedia-Dark#127]
### I would like to be able do the following

I'm not sure if this is a recent change but I recently updated the theme and it seems like the paragraph text is way too high contrast now. `.mw-body-content p` is currently styled with `#ccc` but it would be much easier on the eyes as `#aaa`. For some reason, that's how I remember it looking too until I updated the style today.

**Comment by the-j0k3r** [comment]
Feel free to use https://github.com/StylishThemes/Feature-Override-Styles/blob/master/wikipedia-dark-gray-text-colors.user.css

You can pretty much choose what you want, though in some places links will be white when they should be blue, and so far I cant override that in some areas.

**Comment by Poorchop** [comment]
I know that I can modify it on my end and I already have, I'm just saying that it would be a good idea for the sake of everyone to revert to low contrast text. Looking at the screenshot in the readme, I know that I'm not remembering incorrectly because aside from the mobile screenshot, the text is low contrast. Having bright white text against a dark background as it is now doesn't really make the dark theme any easier on the eyes.

**Comment by the-j0k3r** [comment]
Im not saying you need to edit your style, just use the wikipedia-dark-gray-text-colors.user.css to customize the text brightness to your liking.

As for base theme it stays, simply because ppl ask me to make it brighter, some want it darker and this is why if you dislike the defaults wikipedia-dark-gray-text-colors.user.css exists to fill this need.
