### ISSUE TITLE
Country flags' colors are inverted

### ISSUE THREAD

**Issue by guitarjorge24** [StylishThemes/Wikipedia-Dark#14]
In the page https://en.wikipedia.org/wiki/Greek_language the colors of the country flags gets inverted. 
The issue gets fixed by removing the following code:
.infobox img[src*=".svg"]
Is there a reason to keep that code in place/

**Comment by Mottie** [comment]
Hi @guitarjorge24!

Without that style, then some chemical structure images, like [cholesterol](https://en.wikipedia.org/wiki/Cholesterol), end up being too dark. I could make the selector more specific:

```css
.infobox img[alt*="structure"][src*=".svg"],
```

to make it work in that very specific instance, but then other pages end up being dark because not all have `alt` text - see [aspirin](https://en.wikipedia.org/wiki/Aspirin) & [tylenol](https://en.wikipedia.org/wiki/Paracetamol).

You're right though, the selector as it is right now does mess up a lot of images, and [logos](https://en.wikipedia.org/wiki/Python_(programming_language))

**Comment by Mottie** [comment]
So, I changed the selector to include `[alt*="structure"]` but I would like help finding a better selector.

Also it would be awesome if we could start a list of pages to check.

* https://en.wikipedia.org/wiki/Greek_language
* https://en.wikipedia.org/wiki/Cholesterol
* https://en.wikipedia.org/wiki/Aspirin
* https://en.wikipedia.org/wiki/Paracetamol
* https://en.wikipedia.org/wiki/Python_(programming_language)

**Comment by Poorchop** [comment]
I think you would have to add a similar selector but with `[alt*="skeletal"]` in the case of paracetamol and cholesterol. The country flags also have the `.flagicon` class, which should let you add exclusions with `:not()`, but I think your current approach is better - it's broader but not too broad.

**Comment by guitarjorge24** [comment]
Thanks for all the fixes! Oh I didn't know I could invert them by holding down the mouse button, nice to know!
