### ISSUE TITLE
White background on Spanish versions of pages

### ISSUE THREAD

**Issue by guitarjorge24** [StylishThemes/Wikipedia-Dark#15]
On this Spanish page the text inside a table has white background so it's hard to read.
https://es.wikipedia.org/wiki/Anexo:Episodios_de_Digimon_Adventure

On this other page, the infobox titles have white background:
https://es.wikipedia.org/wiki/Digimon_Adventure

**Comment by Mottie** [comment]
Hi @guitarjorge24!

Ok, all fixed, thanks for reporting this problem!

**Comment by guitarjorge24** [comment]
Thanks! The background on the tables from the first link are fixed but it seems like the infobox titles on the second link are still very bright (unlike the english version of the page which has dark grey title bars).
![spanish infobox](https://cloud.githubusercontent.com/assets/12472021/11968615/28687768-a8dc-11e5-9b11-5aeb58a08440.PNG)

**Comment by Mottie** [comment]
Because the style of *every* cell (`th` in this case) is done by adding an inline style:

```html
<th style="background:#ccccff;">
```

It is pretty much impractical for us to cover every situation. I mean, this time we could add this css to style that color:

```css
th[style*="background:#ccccff"] { background-color: #333 !important; }
```

But on another page the style could have been added like any of these cases:

```html
<th style="background-color:#ccccff;"> <!-- color -->
<th style="background:#CCCCFF"> <!-- all caps -->
<th style="background-color: #CCCCFF;"> <!-- color & caps -->
<th style="background: #ccccff"> <!-- space between : & # -->
```

So, it would be best to cover all these situations as well... And to do that for 65,535 colors would make me want to gouge my eyes out with a crowbar.

**Comment by guitarjorge24** [comment]
Ah, I didn't realize it used inline HTML. I understand that it would be impractical to do that, not to mention the cases where colors are specified as RGB like rgb(204, 204, 255)....

I'm not very acquainted with how the code in Wikipedia works so could you tell me, do all infoboxes use inline HTML for the background color in their title? Why would the HTML from one infobox be different from other infoboxes? I guess there are different infobox templates for different languages? If so, is it possible for me to edit the template used by the page in question to make the code uniform for all the Wikipedia pages that use the template?

**Comment by Mottie** [comment]
I haven't seen the inline styles of Wikipedia use rgb colors, thank goodness, but there really is no consistency across any pages.

For example: Look at how the seasons of [The Arrow](https://en.wikipedia.org/wiki/List_of_Arrow_episodes) are colored (all shades of green probably because of the series), then look at [The Simpsons](https://en.wikipedia.org/wiki/List_of_The_Simpsons_episodes) - inconsistent, random colors.

**Comment by guitarjorge24** [comment]
I see why some pages might a different colors like the green in The Arrow but I'm still wondering why some would use the same color but in a different format. For example, some would use "background: #CCCCFF" (with the space, upper case) and some others might use "background:#ccccff" (without the space, lower case). 

I don't know how a person who edits Wikipedia would edit the background colors of infoboxes, do they have to type in the HTML (which would lead to inconsistency)? However, it seems to me like the color of the infobox in the 2nd link I provided is the default color of infoboxes because I can't see any specification of color when I try to edit the Wikipedia page. If it uses a default color, why would there be an inconsistency between the code of infoboxes on different pages that use the same default color? Sorry for asking so many questions

**Comment by Mottie** [comment]
I don't have all the answers. Try asking the people at Wikipedia.

**Comment by guitarjorge24** [comment]
Alright, thanks
