### ISSUE TITLE
Bad contrast in table with colored cells

### ISSUE THREAD

**Issue by drago333** [StylishThemes/Wikipedia-Dark#163]
The cells of the table have colored background so with the theme default white font color the text becomes hardly readable.

[Timeline of discovery of Solar System planets and their moons – Prehistorically discovered](https://en.wikipedia.org/wiki/Timeline_of_discovery_of_Solar_System_planets_and_their_moons#Prehistorically_discovered)

![Timeline_discovery_Solar_System#Prehistorically](https://user-images.githubusercontent.com/60980007/108590914-a793a500-736e-11eb-847b-fbffeed359db.png)

**Comment by AfroThundr3007730** [comment]
This one was just bad styling of the wikitable, which I've [now edited](https://en.wikipedia.org/wiki/Special:PermaLink/1008129767#Prehistorically_discovered) to make the cells inherit their color from the rows.

<details><summary>Before edit</summary>

![before](https://user-images.githubusercontent.com/7613032/108635117-6803b080-7475-11eb-9bb9-d7d3d17a71d0.png)
</details>

<details><summary>After edit</summary>

![after](https://user-images.githubusercontent.com/7613032/108635122-6df99180-7475-11eb-8fdd-6399b343b794.png)
</details>

**Comment by the-j0k3r** [comment]
> Afterwords, the style's existing fixes solve the rest.

So all colors removed which breaks the idea of having color coded backgrounds...

**Comment by AfroThundr3007730** [comment]
> So all colors removed which breaks the idea of having color coded backgrounds...

Considering the number of articles that have color-coded tables in various forms, with different types of foreground matter (text, pictures, diagrams, etc.), I think handling all but the common cases would probably require a style generator. It would need to not only produce the darker versions of the background, but assess the contrast with foreground text and adjust each accordingly. Otherwise, a color pairing that looks fine in one article might be illegible when used in another, and unfortunately, a good majority of the wiki templates haven't been converted to use TemplateStyles yet, so classes are rare (and won't help with article-specific tables anyway).

I wonder if dark table background colors might be better handled as a userscript, in that case...

**Comment by the-j0k3r** [comment]
Problem is there is no way to do style generation of inline color styles. These will always will need to be handled manually until theres a better way, that would maybe need someone to write a dedicated js module for the task or something else.

Also the only way to assess and generate lightness/darkness would be to use `preprocessor stylus` and use stylus lang, the current wikipedia style is incompatible with that preprocessor as is.

A userscript also possible to do such computation, but again until there's a robust solution the best way is to manually override pages like this because the table colors matter.

Having said that, Im not deving this anymore, so Im OK with whatever you decide or will decide.
