### ISSUE TITLE
various issues on german wiki - bright background/missing colors

### ISSUE THREAD

**Issue by hauk92** [StylishThemes/Wikipedia-Dark#170]
Sorry this issue got a bit large, feel free to yell at me to split it.
Also there are probably a lot more issues regarding election results, see https://de.wikipedia.org/wiki/Liste_von_Wahlen

* **Browser**: Firefox
* **Operating System**: Windows 10
* **Link to page with the issue**: 
### Bright background:
https://de.wikipedia.org/wiki/Wikipedia:Hauptseite
https://de.wikipedia.org/wiki/Wikipedia:Miniaturenwettbewerb
https://de.wikipedia.org/wiki/Wikipedia:Sprachen
https://de.wikipedia.org/wiki/Inuit_Ataqatigiit#Einzelnachweise
https://de.wikipedia.org/wiki/Monaco#Klima
### Missing colours etc:
https://de.wikipedia.org/wiki/Parlamentswahl_in_Gr%C3%B6nland_2021
https://de.wikipedia.org/wiki/Parlamentswahl_in_Gr%C3%B6nland_2021#Umfragen
https://de.wikipedia.org/wiki/Bundestagswahl
https://de.wikipedia.org/wiki/Bundestagswahl#Ergebnisse
https://de.wikipedia.org/wiki/Wikipedia:Statistik#Statistiken_zu_sehr_aktiven_Autoren

* **Screenshot**:
### Bright background:
![grafik](https://user-images.githubusercontent.com/47572039/114078591-72ed9580-98a9-11eb-877b-9f75379dfbde.png)
![grafik](https://user-images.githubusercontent.com/47572039/114078721-90226400-98a9-11eb-9141-bceac1307a34.png)
![grafik](https://user-images.githubusercontent.com/47572039/114078758-9c0e2600-98a9-11eb-99eb-69d130503eff.png)
![grafik](https://user-images.githubusercontent.com/47572039/114078794-a7615180-98a9-11eb-953c-deb5ae61493d.png)
![grafik](https://user-images.githubusercontent.com/47572039/114080601-dd073a00-98ab-11eb-868a-709e267eaaf4.png)
### Missing colours etc:
![grafik](https://user-images.githubusercontent.com/47572039/114079505-9107c580-98aa-11eb-8755-52fb6932464d.png)
![grafik](https://user-images.githubusercontent.com/47572039/114079340-61f15400-98aa-11eb-86cf-9194f31c0519.png)
![grafik](https://user-images.githubusercontent.com/47572039/114079835-f1970280-98aa-11eb-9165-e0635cdbc084.png)
![grafik](https://user-images.githubusercontent.com/47572039/114079923-083d5980-98ab-11eb-8f29-e04139d6c9cd.png)
![grafik](https://user-images.githubusercontent.com/47572039/114080038-302cbd00-98ab-11eb-8032-b062fff95694.png)

**Comment by AfroThundr3007730** [comment]
@hauk92 So the first half of the issue is solved now, albeit with a lot more `!important` rules than I would like. This is why I don't like inline styles, but it seems dewiki hasn't fully joined the [TemplateStyles](https://www.mediawiki.org/wiki/Extension:TemplateStyles) trend yet.

As for the second part of the issue, fixing those pie charts and bar graphs would essentially require exempting those specific colors from the generic `div[style*="background:"]` rule, which will probably poke holes in the style elsewhere. If there were some classes or something to write a selector against, it'd be a different story.

The image background contrast issue is a war that has been waged since this style was first started, and no matter what we do, there will always be images that have the wrong background. We can add selectors specifically for those images, but more will appear. Or we could just make all thumbnail backgrounds white and override [this rule](https://github.com/StylishThemes/Wikipedia-Dark/blob/541eb4f8925ca5ef602011f3c80504481fa3c601/wikipedia-dark.user.css#L3006) for dewiki.

If you've got a better method of fixing those, feel free to submit a PR, but for now I'm going to leave them be.
