### ISSUE TITLE
Just A Few Issues But Basically Perfect! 

### ISSUE THREAD

**Issue by PersonDudeMan** [StylishThemes/Wikipedia-Dark#34]
I really like this theme! I needed just a simple dark theme for Wikipedia and this is it! It's great so far I just have a few issues. For example, the visited link text is a dark blue color and it's a little less readable since it's dark on dark. If I could offer a suggestion, maybe a purple color for visited links could help make it more readable? Also, for charts whenever there's an "N/A" in a column, the column is grey with black text which I cannot read at all and only knew it was saying "N/A" when I highlighted the text. You can see what I mean in the images below.  Other than that it's great!
![image](https://user-images.githubusercontent.com/38995688/39658777-06395a80-4fcf-11e8-8eff-09131a81ec96.png) 
![image](https://user-images.githubusercontent.com/38995688/39658783-26118d96-4fcf-11e8-8723-6708a57ddada.png)

**Comment by Mottie** [comment]
Hi @PersonDudeMan!

Thanks! We try hard to make everything work.

The Visited link color is actually customizable. On userstyles.org, click the "Customize Settings" button and then click on the "Visited link color" color swatch.

![](https://user-images.githubusercontent.com/136959/39658876-ff94cf94-4fe1-11e8-9559-0132ce7e41b4.png)

As for the "N/A", please share a link to the page. Table background colors are really hard to fix since wikipedia doesn't have a fixed color palette, all table cells use inline style definitions - see [limitations](https://github.com/StylishThemes/Wikipedia-Dark#limitations). In this case, I'll need to see the table to target the exact color.

**Comment by PersonDudeMan** [comment]
Oh dang! That's on me for not looking closely at the Stylish page! This is the page I was looking at. The table is in the "Tours" section. https://en.wikipedia.org/wiki/Dream_Theater

**Comment by Mottie** [comment]
Done! And thanks for reporting this problem.
