### ISSUE TITLE
Found another table that doesn't play well with the theme

### ISSUE THREAD

**Issue by HerrHulaHoop** [StylishThemes/Wikipedia-Dark#36]
Found another [table](https://en.wikipedia.org/w/index.php?title=Starbreeze_Studios#Games_developed) where the notes footer doesn't seem to conform to the dark theme. 

![Screenshot with HTML view](https://user-images.githubusercontent.com/31934788/42690923-cdcf3314-86c3-11e8-92ea-94ee9f043ef6.png)

Let me know if you require any further details.

Thanks!

**Comment by Mottie** [comment]
Hi @HerrHulaHoop!

I just fixed this locally. If you're using Stylus or Freestyler, then install Wikipedia-Dark directly from this repository, because I think it's time to stop supporting userstyles.org.

Sorry, but I don't think we'll be updating that site any more. [OpenUserCSS](https://openusercss.org/) is an up-and-coming user style web site. It still needs a bit of work, but we'll definitely move our style there once we can.

If you're not using Stylus or Freestyler, then I'm sorry... the only option you'll have would be to manually add the changes from https://github.com/StylishThemes/Wikipedia-Dark/commit/c5560ac42532051946a63745bbe930c76e58a317 and https://github.com/StylishThemes/Wikipedia-Dark/commit/5060683656da6c2b353097e414750842cb6e6707 to get up to date.
