### ISSUE TITLE
Table that doesn't adapt to dark theme

### ISSUE THREAD

**Issue by HerrHulaHoop** [StylishThemes/Wikipedia-Dark#38]
Found another [table](https://en.wikipedia.org/wiki/Wizardry#Main_series) where the cells don't conform to the dark theme. 

![Screenshot with HTML view](https://user-images.githubusercontent.com/31934788/42940236-558a22da-8b76-11e8-83e6-e61647ec89b3.png)

As per your instructions in the previous issue post, I've switched to Stylus and obtained the theme from usercss. So I guess this should be the latest version.

Do let me know if I should provide any further details.

Thanks!

**Comment by Mottie** [comment]
Hi @HerrHulaHoop!

Thanks for reporting this problem. Please be aware that we can't fix *every* mis-colored table row/cell/content. Wikipedia uses inline styling so it is very difficult to target every single possible variation - see [our readme](https://github.com/StylishThemes/Wikipedia-Dark#limitations). I'll go ahead and fix this one since it's off-white.
