### ISSUE TITLE
Restore the color scheme of .mbox and other warning boxes

### ISSUE THREAD

**Issue by AfroThundr3007730** [StylishThemes/Wikipedia-Dark#79]
Wikipedia and its sister sites, have a complex system of notice and warning templates of varying severity, which make use of a color scheme to distinguish between message type and severity.

Right now, most of the warning and notice message boxes are all reduced to the same color (`--gray-2`/`#222222`) instead of a darker variation of the original color scheme. This removes essential contextual data when using our dark theme, and should get corrected eventually.

This may take a bit of doing in the style's current state though.

**Comment by AfroThundr3007730** [comment]
One example on WP (first encountered on the page deleted message) here:
https://github.com/StylishThemes/Wikipedia-Dark/blob/69f52ad3387d65438a76496cb99f85a88b78ef1e/wikipedia-dark.user.css#L448-L453

Another one from MediaWiki (not added to main style, since I've only seen it there):
https://github.com/StylishThemes/Wikipedia-Dark/blob/69f52ad3387d65438a76496cb99f85a88b78ef1e/wikipedia-dark.user.css#L1003-L1006

ArchWiki has several of them (and most are styled correctly), but many on Wikipedia are not. I'll start colorizing them as I find them.

**Comment by the-j0k3r** [comment]
IIRC I did the Archwiki ones that work, the remainder is up for grabs though its  a mess due to most of these being done incorrectly, If I have time and patience to touch these, I may have a go. Again I would rather do a re-write and use a generator rather than spend time untangling cooked spaghetti.

**Comment by the-j0k3r** [comment]
I just pushed some more fixes to for mainpage, also, do you realize this lack of colors is by design, its on the readme, essentially instead of hunting these or fix them as they were reported, it was done all in one color with those sweeping selectors we both dont like =)

Generator is closer than further with https://github.com/StylishThemes/GitHub-Dark/pull/1019, but silverwind isn't as active these days, and that slows down these changes.

**Comment by the-j0k3r** [comment]
And more fixes re this in https://github.com/StylishThemes/Wikipedia-Dark/commit/9d9fa69a5c6d4db79f1d702d2e144044fbfef8e5

**Comment by the-j0k3r** [comment]
heres more work https://github.com/StylishThemes/Wikipedia-Dark/commit/4e609667466aed326e68f0ab1176ddd951c1012b this could definitely be imported into new style

**Comment by the-j0k3r** [comment]
Ive pushed more fixes relating to this, but please note, that Im keeping these boxes colors as much as possible true to default just darker.

Lets avoid opinionated styles that dont go along with that, simply its not a good idea from users that are coming to a dark style, dont see warning boxes that are completely different for same thing, e.g yellow should be brown not green not red not purple etc.

**Comment by the-j0k3r** [comment]
Yea, this isnt gonna go any further from my side. Its consuming a stupid amount of time and its an impossible job considering we support 50 million wikis with 99999 billion pages, tracking down each inline style is not my idea of fun.

For a style I dont really use, yea, this is it.

Also read https://github.com/StylishThemes/Wikipedia-Dark#limitations

Main screenshot on readme also needs updating along with anything else related.

**Comment by AfroThundr3007730** [comment]
@the-j0k3r Thanks for all your work fixing this mess. Perhaps eventually we can move to using that generator so stuff like this will no longer be necessary (or at least significantly less work). I'll continue playing whack-a-mole to clean up the regressions in the meantime.

Also, it's looking a lot nicer now. :)

**Comment by the-j0k3r** [comment]
> Also, it's looking a lot nicer now. :)

Yea it is. Sadly I have other projects. But generator is coming along just needs to finalize replacing grunt, then it should be ready.

Mind, this still means all the inline styes wont be styled, except with this work of styling inline stuff, its a definate start even for rewrite, since this can be used as is.

Also the images styling is getting better too. I saw to that. Basically all that is not user content or pictures like https://github.com/StylishThemes/Wikipedia-Dark/blob/master/wikipedia-dark.user.css#L2302-L2371 also in other specific sites

**Comment by the-j0k3r** [comment]
I think this is pretty much done, whatever is left is up to the your friendly neighborhood Spider-man.
