### ISSUE TITLE
Give users more changeable colors

### ISSUE THREAD

**Issue by kfdz277** [StylishThemes/Wikipedia-Dark#96]
I feel like this extension could be tuned to perfection if we could change the colors of stuff like the background itself (table heading text color, table heading bg color, etc.) through the "Manage style" UI. I imagine that, for some, the default colors have too strong of a contrast. I don't think it'd be out of your way, and would at the very least service my needs :P

**Comment by the-j0k3r** [comment]
@kfdz277 That you for this request.

>  I don't think it'd be out of your way


The bad news.

It would and not something anyone wants to tackle to service the needs of a couple of users due to complexity of style, how its written and the sheer number of issues we need to get past before going down any route like this, not a simple matter at all.

The good news.

It probably would be possible to override some elements in a new smaller style (we have done that for Github Dark a few times)  that would work along side this style, thats more likely to happen and easier to tackle, but that said, if you really want something like that, youll need to wait for someone )even me) to be interested in doing this.

So anyone interested in this please thumbs up this comment (mine) so I can gauge interest. in this request.

@AfroThundr3007730 ping what say ye.

Thanks for understanding.

**Comment by kfdz277** [comment]
How about the regular font color? I would never have guessed that it was actually complicated though lol, totally understand your apprehension. My main issue is that the background and the font don't have enough contrast, so it comes off as being hard to read.

**Comment by the-j0k3r** [comment]
If you give me specific for instances in screenshots and links to pages I'll try to do an override style, but again its not as simple as adding the options to existing style, because we dont organize just font color rules, one rule can have text color and other elements colors also, so these would need to be separated not to mention text colors are in several places with several shades of white, for different wiki based sites. So it has to work

Its easier and faster to override in a small style that re-writing most of the style to add options and not fix the actual issues behind in a huge OLD style like this. So provide the info I need and Ill try to make an override style when I have a minute.

**Comment by AfroThundr3007730** [comment]
I think that providing support for user configuration inline would basically require a complete rewrite of the desktop style. Not that it would be too difficult, just time consuming, and we'd be playing unstyled element whack-a-mole for a few weeks afterwards. The majority of the rules in this style are from those accumulated fixes anyway. A rewrite may be the proper way ahead with this though, for future sustainability.

As far as doing it in a separate style, that's certainly possible, but we'll end up writing ridiculous selectors in an attempt to override all the `!important` rules sprinkled everywhere, much as we have to do now in the main style. This would require the least ammount of immediate effort though.

**Comment by the-j0k3r** [comment]
We already have https://github.com/StylishThemes/Feature-Override-Styles so I can start converting the styles we already have for GitHub Dark

Further reading https://github.com/StylishThemes/GitHub-Dark/issues/1008

**Comment by the-j0k3r** [comment]
@kfdz277 See https://raw.githubusercontent.com/StylishThemes/Feature-Override-Styles/master/wikipedia-dark-gray-text-colors.user.css

That may improve in the future but for now its text colors only.

Any contributions welcome.

**Comment by the-j0k3r** [comment]
@kfdz277 feedback on the script above?

**Comment by kfdz277** [comment]
I definitely dig this, sorry for being late. Much easier on the eyes imo.

**Comment by kfdz277** [comment]
Hey y'all, love the work you guys did and my eyes treasure it every day. However, some small things have been breaking over time. Seems like Wikipedia has a new element for the language picking section, and the script doesn't cover it rn, as well as some boxes on wiki homepages. Here's a pic of everything I mean using WikiUniversity.

![image](https://user-images.githubusercontent.com/55974345/81617842-2ad1a480-93b4-11ea-8c65-d34f52b64d5e.png)

**Comment by the-j0k3r** [comment]
@kfdz277 see https://github.com/StylishThemes/Wikipedia-Dark/issues/123, Please avoid in future reporting new unrelated issues in existing issues.

New issues for these are the way to go.

See https://github.com/StylishThemes/Wikipedia-Dark/issues/123 for that.

**Comment by kfdz277** [comment]
i posted here bc i thought the style you gave me was breaking these as opposed to it being part of the core lol sorry

**Comment by the-j0k3r** [comment]
You should test first with the `wikipedia-dark-gray-text-colors.user.css` and then without to determine where the issue is, the  open a bug in the relevant repo.

Also for the background colors see https://github.com/StylishThemes/Wikipedia-Dark/issues/119 it has a workaround you may like to use.
